/// runfail: Assertion failed: `x == 2`

def main() {
    let x = 1
    assert x == 1
    assert x == 2, "x should be 2"
}