/// fail: Continue statement outside of loop

def main() {
    continue
}
